### ISSUE TITLE
Generators, async/await?

### ISSUE THREAD

**Issue by bySabi** [pbastowski/ecmascript-extras#1]
Hi @pbastowski I need await on client side then I add your package. But Still have 'Unexpected token' with this lines:

```
function async foo () {
  return await;
}
```

I need something more, regenerator `runtime.js` maybe?
Thanks for your work

**Comment by pbastowski** [comment]
Thanks, I'll check why that's happening, but....

You actually got the syntax the wrong way around and `return await` is an error, try this:

``` javascriot
async function foo () {
  return await 123;
}

var a = foo().then(d =>console.log(d));
```

To test if your code actually works go here http://babeljs.io/repl/

**Comment by bySabi** [comment]
Thanks for code fix, I don´t check at all before copy-paste :-(
Anyway still no work.
Do you test it on your own ?

**Comment by bySabi** [comment]
I think that for `generators` facebook regenerator runtime is needed, like do this package: https://github.com/grigio/meteor-babel/blob/master/package.js
Then maybe we need a additional package just for generators cause not all developers want/need the extra overhead.
Ideally, in my world, I'll like to see async/await with regenerator on client side and with `promise`(fibers) package on server. And when meteor 1.3 is arrived, just remove this package without touch my code.

**Comment by pbastowski** [comment]
The generators runtime is already included by the mdg `ecmascript` package, but not all of it. Specifically, async function helpers are not included. I'm may have a workaround, where I can add the missing runtime helpers. But for now I'm a bit busy with other work.

**Comment by bySabi** [comment]
I didn't know about generators runtime on `ecmascript`.
When you can add it update README.
Thanks for your time.
